#!/usr/bin/env bash
# This script tells the story of the /etc/passwd file

# Read /etc/passwd line by line
while IFS=':' read -r username _ uid gid info home shell; do
    # Extract the user's password field
    password=$(grep "^$username:" /etc/shadow | cut -d ':' -f2)

    # Display the story
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
