#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Counter to keep track of the number of times "Best School" is displayed
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    echo "Best School"
    ((counter++))
done
