#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and prints messages for specific iterations

# Counter to keep track of the number of iterations
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    ((counter++))
done
